---
# tasks file for hoplacloud.lamp

- name: Ensure root password is allowed in SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: "PermitRootLogin yes"

- name: restart service ssh
  systemd:
    state: restarted
    name: ssh

- name: restart apache
  service: name=apache2 state=restarted

- name: Log variables to file
  template:
    src: logs.j2
    dest: /root/Oneclick-wp-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.txt
    owner: root
    group: root
